apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mindbox-web-testsre-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mindbox-web-testsre-deployment
  minReplicas: 1  # Ночью масштабировать вниз
  maxReplicas: 6  # предотвращает over-scaling делаем запас
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60